export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_USER_EXISTS: "AUTH_USER_EXISTS",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  INVITATION_NOT_FOUND: "INVITATION_NOT_FOUND",
  INVITATION_SLUG_EXISTS: "INVITATION_SLUG_EXISTS",
  INVITATION_NOT_PUBLISHED: "INVITATION_NOT_PUBLISHED",
  TEMPLATE_NOT_FOUND: "TEMPLATE_NOT_FOUND",
  RSVP_NOT_FOUND: "RSVP_NOT_FOUND",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;